---
- hosts: all

  # add users here
  vars:
    users:
    - zhihaow

  tasks:
    # create users and add to p4-restart and sudo group
    - name: Create new user and add to p4 group
      become: true
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: sudo, p4-restart
        append: yes
        password: $6$mysecretsalt$ul12L2a.WJcoW06WoWCAje72i41pPT5v6OIB71.QGV9uBfZSjFc081JCE5uluOQOdSuwE7Rvi5boXVLINrNXx/ # defualt password
        update_password: on_create
        state: present
      with_items: "{{ users }}"