- name: Ensure requirements in place
  package:
    name:
      - libguestfs-tools
      - python3-libvirt
      - python3-lxml
      - libnss-libvirt
      - libvirt-daemon-system
      - qemu-system
      - bridge-utils
    state: present

- name: Start service libvirt
  service:
    name: libvirtd
    state: started

- name: Add admin user to libvirt group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: libvirt
    append: yes
    state: present

- name: Add bridge connection
  ansible.builtin.nmcli:
    conn_name: "{{ bridge_name }}"
    ifname: "{{ bridge_name }}"
    type: bridge
    ip4: "{{ bridge_host_ip }}"
    gw4: "{{ bridge_host_gw }}"
    stp: false
    state: present

- name: Add bridge-slave connection
  ansible.builtin.nmcli:
    conn_name: bridge-slave-{{ bridge_host_iface }}
    ifname: "{{ bridge_host_iface }}"
    type: bridge-slave
    hairpin: false
    master: "{{ bridge_name }}"
    state: present

- name: Define a new bridged network
  community.libvirt.virt_net:
    command: define
    name: bridged-network
    xml: '{{ lookup("template", "libvirt-network.xml.j2") }}'

- name: Ensure network started
  community.libvirt.virt_net:
    name: bridged-network
    state: active

- name: Autostart network
  community.libvirt.virt_net:
    name: bridged-network
    autostart: yes

- name: Configure libvirt VM name resolution
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: 'hosts:          files mdns4_minimal [NOTFOUND=return] libvirt dns myhostname mymachines'


