- name: Dependencies
  package:
    name: 
      - "members"
    state: present

- name: Create home directory .restart in {{ ansible_user }} user
  ansible.builtin.file:
    path: "{{ restart_install_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: chmod g-w p4studio/CMakeLists.txt
  ansible.builtin.file:
    path: "{{ sde }}/p4studio/CMakeLists.txt"
    mode: 0644

- name: Allow the {{ p4_restart_group }} group to run sudo apt
  community.general.sudoers:
    name: p4-restart-tenants-permissions
    group: "{{ p4_restart_group}}"
    commands: 
      - /usr/bin/apt
      - "{{ sde }}/run_switchd.sh"
      - "{{ sde_install }}/bin/p4-build"
      - /usr/local/bin/p4
      - /usr/local/bin/p4-build
      - /usr/bin/pkill bf_switchd

- name: Set cpability to network access for python code
  community.general.capabilities:
    path: /usr/bin/python3.8
    capability: cap_net_raw,cap_net_admin=eip
    state: present

- name: Set capability to network access for tcpdump
  community.general.capabilities:
    path: /usr/sbin/tcpdump
    capability: cap_net_raw,cap_net_admin=eip
    state: present

- name: Create deny-ssh group
  ansible.builtin.group:
    name: deny-ssh
    state: present

- name: Add DenyGroups to sshd config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/10-deny-ssh.conf
    line: 'DenyGroups deny-ssh'
    state: present
    create: true
  notify:
    - Restart sshd

- name: Copy enable script to {{ restart_install_dir }}
  ansible.builtin.template:
    src: "enable_ssh_access.sh.j2"
    dest: "{{ restart_install_dir }}/enable_ssh_access.sh"
    mode: 0755